version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: jobscraper
      POSTGRES_USER: jobuser
      POSTGRES_PASSWORD: jobpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: